This commit add a new breadcrump component
lflondonol92/prft-aem-bootcamp-latam-q2 pull request #32
Opened 2024-05-31 13:01 UTC by emelmoraperf

This commit add a new breadcrump component

2024-05-31 20:00 UTC, valMoncadaS requested changes

2024-05-31 20:00 UTC, valMoncadaS commented on ui.frontend/src/main/webpack/components/_breadcrumb.scss
> +    font-weight: $font-semibold;
font weight should not be bold for all items. Please review colleagues work and fix

2024-06-13 14:23 UTC, joseVperficient approved these changes

2024-06-13 21:24 UTC, joseVperficient approved these changes

2024-06-13 21:25 UTC, joseVperficient approved these changes

2024-06-13 21:26 UTC, joseVperficient approved these changes

2024-06-13 21:26 UTC, merged