feat: Add breadcrumb component
lflondonol92/prft-aem-bootcamp-latam-q2 pull request #34
Opened 2024-05-31 17:46 UTC by SantiagoRodH

![Screenshot 2024-05-31 at 12 42 07 PM](https://github.com/lflondonol92/prft-aem-bootcamp-latam-q2/assets/170354505/b16f25b9-dec5-4a6e-a459-bb112609956e)

- In Home page
![Screenshot 2024-05-31 at 12 39 42 PM](https://github.com/lflondonol92/prft-aem-bootcamp-latam-q2/assets/170354505/24aee5b6-d670-4948-a92d-46586a9e3487)

- Hide in navigation option in Overview page  set to true
![Screenshot 2024-05-31 at 12 39 49 PM](https://github.com/lflondonol92/prft-aem-bootcamp-latam-q2/assets/170354505/9edbb446-65a5-4791-aadb-b70f9e057ada)

2024-05-31 19:41 UTC, lflondonol92 requested changes

2024-05-31 19:41 UTC, lflondonol92 commented on ui.apps/src/main/content/jcr_root/apps/aem-bootcamp/components/structure/breadcrumb/.content.xml
> +    jcr:title="Breadcrumb Component"
the jcr:description is missing

2024-05-31 19:41 UTC, lflondonol92 commented on core/src/main/java/com/aembootcamp/core/models/BreadcrumbModel.java
> +    if(currentPage != null) {
Use the template of the currentPage and not the path to verify this.

2024-05-31 19:41 UTC, lflondonol92 commented on core/src/main/java/com/aembootcamp/core/models/BreadcrumbModel.java
> +  public Boolean getIsHome() {
rename this method. getIs is a bad naming strategy. Please rename it to isHomePage.

2024-05-31 19:41 UTC, lflondonol92 commented on ui.apps/src/main/content/jcr_root/apps/aem-bootcamp/components/structure/breadcrumb/breadcrumb.html
> +<sly data-sly-test="${!breadcrumb.isHome}" data-sly-use.template="core/wcm/components/commons/v1/templates.html">
breadcrumb.homePage

2024-06-14 18:03 UTC, joseVperficient approved these changes

2024-06-14 18:03 UTC, merged