New footer Component was created
lflondonol92/prft-aem-bootcamp-latam-q2 pull request #72
Opened 2024-06-19 18:38 UTC by emelmoraperf

New footer Component was created
![image](https://github.com/lflondonol92/prft-aem-bootcamp-latam-q2/assets/170551914/e983e396-3336-464f-b167-bd6e74c89df8)

2024-06-20 15:07 UTC, lflondonol92 commented
Please update the screenshots to include the tablet and mobile views. Additionally, the footer navigation doesn't look like working ok. 
Please review Camilo's PR to copy the styles of that component.

2024-06-25 19:18 UTC, valMoncadaS requested changes

2024-06-25 19:18 UTC, valMoncadaS commented on ui.content/src/main/content/jcr_root/content/experience-fragments/aem-bootcamp/us/en/site/footer/master/.content.xml
> +                    navigationRoot="/content/aem-bootcamp/us/en/testhomepage2"/>
separator is missing

2024-06-26 17:04 UTC, valMoncadaS approved these changes

2024-06-26 19:03 UTC, merged