Feature/ccta/aembootcamp 002
lflondonol92/prft-aem-bootcamp-latam-q2 pull request #9
Opened 2024-05-22 20:23 UTC by cctorres

Extend WCM Core Components page v2
Create an editable template type called "Base Template"

2024-05-22 21:18 UTC, valMoncadaS requested changes

2024-05-22 21:18 UTC, valMoncadaS commented on ui.content/src/main/content/jcr_root/conf/aem-bootcamp/settings/wcm/template-types/base-template/initial/.content.xml
>          <root
The initial values for the XFs are missing

2024-05-22 21:18 UTC, valMoncadaS commented on ui.content/src/main/content/jcr_root/conf/aem-bootcamp/settings/wcm/template-types/base-template/policies/.content.xml
> +            <container
Please confirm if there should be 3 policies instead of 2

2024-05-23 14:49 UTC, lflondonol92 requested changes
Please resolve the comments.

2024-05-23 14:49 UTC, lflondonol92 commented on ui.apps/src/main/content/jcr_root/apps/aem-bootcamp/components/page/.content.xml
> -    componentGroup=".hidden"/>
The hidden property is missing

2024-05-23 14:49 UTC, lflondonol92 commented on ui.apps/src/main/content/jcr_root/apps/aem-bootcamp/components/page/.content.xml
> +    componentGroup="AEM Bootcamp Site - Content"/>
this is not the right group

2024-05-23 14:49 UTC, lflondonol92 commented on ui.content/src/main/content/jcr_root/conf/aem-bootcamp/settings/wcm/template-types/.content.xml
> -    <page/>
Why is the page template type missing?

2024-05-23 15:09 UTC, lflondonol92 approved these changes
Approved

2024-05-23 15:10 UTC, merged